descriptions = new Array("Accessing the Treasurers System Top Previous Next The KellPro Treasurers System is accessed by entering the Username and Password provided by Kell...",
	"Daily Report Top Previous Next Enter topic text here. ",
	"Date Fields Top Previous Next Date fields have unique behavior that allows faster data entry. The shortcuts are listed below. • pressing C on your...",
	"Deposits Top Previous Next Enter topic text here. ",
	"Fields with Special Behavior Top Previous Next need to verify that this information is valid for KTS There are several types of behavior that fiel...",
	"Fiscal Calendar Top Previous Next Enter topic text here. ",
	"G/L Accounts Top Previous Next Enter topic text here. ",
	"Install Latest Version of KTS Top 1. Go to Admin&gt;Update Version 2. This will ask if the user is sure he/she wants to update the system. 3. Clickin...",
	"Journal Entries Top Previous Next Enter topic text here. ",
	"KTS Bookkeeping Top Previous Next The KTS Bookkeeping menu provides the following menu items: Daily Report we know there are monthly, quarterly, e...",
	"KellPro Treasurers System Contents | Index | Search Enter one or more keywords to search ('*' and '?' wildcards are supported): You must have Java...",
	"KTS Tax Module Top Previous Next The KTS Tax Module menu provides the following menu items: Daily Report Deposits Fiscal Calendar G/L Accounts Jou...",
	"Misc Receipts Top Previous Next Enter topic text here. ",
	"Basic Functions - Overview Top Previous Next need to verify that this information is valid for KTS Every KellPro Key System has a few basic functi...",
	"People Top Previous Next Enter topic text here. ",
	"Using the System Screens - KEY Basics Top Previous Next ",
	"Versions Top Enter topic text here. ",
	"Welcome to the KellPro Treasurers System Top Next The KellPro Treasurers System (or KTS) provides a simple, comprehensive approach to bookkeeping ...",
	"Working With Grids Top Previous A grid is a list of detail records inside a main record. A grid allows the user to view, modify and add detail rec...");